/*in next edit change table name to DimStudent to follow dim/fact naming convention*/
DROP TABLE CUSTOM.CUSTOM_EARLY_WARNING_STUDENTS

CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_STUDENTS (
STUDENTKEY INT,
STUDENT_NUMBER INT,
SPED_CLASSIFICATION VARCHAR(100),
SPED_FUNDING VARCHAR(10),
HOMELESS INT,
ELL INT,
SPED INT,
AGE_YEARS INT,
DOB DATE,
EVER_RETAINED INT,
ENROLLMENT_STATUS VARCHAR(50),
SCHOOLID INT,
SCHOOLNAME VARCHAR(50),
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
FULLNAME VARCHAR(100),
GRADELEVEL VARCHAR(5),
HOMEROOM VARCHAR(100));

CREATE INDEX EW_STUDENTS ON CUSTOM.CUSTOM_EARLY_WARNING_STUDENTS (STUDENT_NUMBER);

INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_STUDENTS --(STUDENTKEY,STUDENT_NUMBER,SPED_CLASSIFICATION,SPED_FUNDING,HOMELESS,ELL,SPED,AGE_YEARS,DOB,EVER_RETAINED,ENROLLMENT_STATUS,SCHOOLID,SCHOOLNAME)
SELECT 
S.STUDENTKEY AS STUDENTKEY,
PS.STUDENT_NUMBER AS STUDENT_NUMBER,
--YEARS AT KIPP,
SPED_CLASSIFICATION AS SPED_CLASSIFICATION,
SPED_FUNDING AS SPED_FUNDING,
CSD.HYCP AS HOMELESS,
CSD.ELL AS ELL,
CSD.SPED AS SPED,
DATEDIFF(YY,S.DATEOFBIRTH,GETDATE()) AS AGE_YEARS,
S.DATEOFBIRTH AS DOB,
RE.RETAINED AS EVER_RETAINED,
S.ENROLLMENTSTATUS AS ENROLLMENT_STATUS,
PS.SCHOOLID,
SC.ABBREVIATION,
PS.FIRST_NAME,
PS.LAST_NAME,
PS.LASTFIRST,
PS.GRADE_LEVEL, --current grade level
PS.HOME_ROOM --current home room 
FROM DW.DW_DIMSTUDENT S
LEFT JOIN CUSTOM_STUDENTS CS ON CS.STUDENTKEY = S.STUDENTKEY
LEFT JOIN CUSTOM_STUDENTS_DAILY CSD ON CSD.STUDENTKEY = S.STUDENTKEY AND CSD.FULLDATE = CONVERT(VARCHAR(10),GETDATE(),101)
LEFT JOIN [CUSTOM].[CUSTOM_STUDENTBRIDGE] SB ON SB.SYSTEMSTUDENTID = S.SYSTEMSTUDENTID
LEFT JOIN POWERSCHOOL.POWERSCHOOL_STUDENTS PS ON PS.STUDENT_NUMBER = SB.STUDENT_NUMBER
LEFT JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SC ON SC.SCHOOL_NUMBER = PS.SCHOOLID
LEFT JOIN (SELECT DISTINCT ID, 1 AS RETAINED FROM (SELECT ID,ENTRYCODE,EXITCODE FROM POWERSCHOOL.POWERSCHOOL_STUDENTS
	  UNION ALL
	  SELECT STUDENTID, ENTRYCODE, EXITCODE FROM POWERSCHOOL.POWERSCHOOL_REENROLLMENTS) E
	  WHERE E.ENTRYCODE = 'RE' OR E.EXITCODE = 'R') RE ON RE.ID = PS.ID
