DROP TABLE CUSTOM.CUSTOM_EARLY_WARNING_FACT;

CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_FACT(
STUDENT_NUMBER INT,
STUDENTID INT,
STUDENTKEY INT,
SYSTEMSTUDENTID VARCHAR(25),
TERMKEY INT,
ABSENCES INT,
MEMBERSHIP INT,
UNEXCUSED_ABSENCES INT,
TARDIES INT,
COUNT_OSS INT,
DAYS_OF_OSS INT,
NUM_OF_INCIDENTS INT,
NUM_OF_REFERRAL INT,
GPA FLOAT(5),
NUM_DS_AND_FS INT,
SCALESCORE_MATH INT,
PERCENTILESCORE_MATH INT,
SCALESCORE_READING INT,
PERCENTILESCORE_READING INT,
ANNUALCGI_MATH FLOAT(5),
ANNUALGP_MATH INT,
WINDOWCGI_MATH FLOAT(5),
WINDOWGP_MATH INT,
ANNUALCGI_READING FLOAT(5),
ANNUALGP_READING INT,
WINDOWCGI_READING FLOAT(5),
WINDOWGP_READING INT,
STEP_LEVEL INT,
STEP_PROFICIENCY VARCHAR(20),
[FP LEVEL] INT,
[TARGET LEVEL] INT
);

CREATE INDEX EW_FACT ON CUSTOM.CUSTOM_EARLY_WARNING_FACT (STUDENT_NUMBER,TERMKEY,STUDENTKEY,STUDENTID);

INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_FACT --(STUDENT_NUMBER,STUDENTID,STUDENTKEY,SYSTEMSTUDENTID,TERMKEY,ABSENCES,MEMBERSHIP,UNEXCUSED_ABSENCES,TARDIES,COUNT_OSS,DAYS_OF_OSS,NUM_OF_INCIDENTS,NUM_OF_REFERRAL,GPA,NUM_DS_AND_FS)
SELECT
A.STUDENT_NUMBER,
A.STUDENTID,
A.STUDENTKEY,
A.SYSTEMSTUDENTID,
A.TERMKEY,
A.ABSENCES,
A.MEMBERSHIP,
A.UNEXCUSED_ABSENCES,
A.TARDIES,
B.COUNT_OSS,
B.DAYS_OF_OSS,
B.NUM_OF_INCIDENTS,
B.NUM_OF_REFERRAL,
GPA.GPA,
G.NUM_DS_AND_FS,
SM.SCALESCORE,
SM.PERCENTILESCORE,
SR.SCALESCORE,
SR.PERCENTILESCORE,
GM.ANNUAL_CGI,
GM.ANNUAL_GP,
GM.WINDOW_CGI,
GM.WINDOW_GP,
GR.ANNUAL_CGI,
GR.ANNUAL_GP,
GR.WINDOW_CGI,
GR.WINDOW_GP,
STEP.TESTSCORE,
STEP.PROFICIENCYLEVEL,
[FP LEVEL],
[TARGET LEVEL]
FROM [CUSTOM].[CUSTOM_EARLY_WARNING_ATTENDANCE] A
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_BEHAVIOR] B ON B.STUDENT_NUMBER = A.STUDENT_NUMBER AND B.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_GPA] GPA ON GPA.STUDENT_NUMBER = A.STUDENT_NUMBER AND GPA.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_GRADES] G ON G.STUDENT_NUMBER = A.STUDENT_NUMBER AND G.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_MATH] SM ON SM.STUDENT_NUMBER = A.STUDENT_NUMBER AND SM.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_READING] SR ON SR.STUDENT_NUMBER = A.STUDENT_NUMBER AND SR.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_MATH] GM ON GM.STUDENT_NUMBER = A.STUDENT_NUMBER AND GM.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_READING] GR ON GR.STUDENT_NUMBER = A.STUDENT_NUMBER AND GR.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_STEP] STEP ON STEP.STUDENT_NUMBER = A.STUDENT_NUMBER AND STEP.TERMKEY = A.TERMKEY
LEFT JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_FP] FP ON FP.STUDENT_NUMBER = A.STUDENT_NUMBER AND STEP.TERMKEY = A.TERMKEY
;
