/*
The assessment growth tables are built of off [test_nweamap].[Test_NWEAMAP_MAPRawData_vX] tables.
They will probably be replaced with 16-17 records once the new Fall files are sent to SZ
When updating EWS after the fall window, check that these tables are not dropped first
Eventually create a new table that has all MAP file data from all years in one table

  
DROP TABLE CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_MATH;

CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_MATH (
STUDENT_NUMBER INT,
TESTSUBJECT VARCHAR(20),
TESTPERIOD VARCHAR(10),
YEARID INT,
TESTDATE DATE,
ANNUAL_CGI FLOAT(5),
ANNUAL_GP INT,
WINDOW_CGI FLOAT(5),
WINDOW_GP INT,
SCHOOL_NUMBER INT,
TERMKEY INT)

CREATE INDEX EW_ASSESSMENT_GROWTH_MATH ON CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_MATH (STUDENT_NUMBER,TERMKEY);

INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_MATH
SELECT 
 F15_SUB.*,
 COALESCE(T.TERMKEY,-1)
FROM (
	SELECT 
		STUDENTID,
		MEASUREMENTSCALE,
		'Fall' AS TERMNAME,
		25 AS YEARID,
		CONVERT(DATE,TESTSTARTDATE) TESTDATE,
		[FallToFallConditionalGrowthIndex] ANNUAL_CGI,
		[FallToFallConditionalGrowthPercentile] ANNUAL_GP,
		NULL WINDOW_CGI,
		NULL WINDOW_GP,
		SC.SCHOOL_NUMBER
		FROM [test_nweamap].[Test_NWEAMAP_MAPRawData_v2] F15
		JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SC ON SC.NAME = F15.SCHOOLNAME 
		WHERE STUDENTID != 'StudentID'
		AND MEASUREMENTSCALE = 'Mathematics'
	) F15_SUB
LEFT JOIN CUSTOM.CUSTOM_EARLY_WARNING_TERMS T ON T.SCHOOLID = F15_SUB.SCHOOL_NUMBER AND F15_SUB.TERMNAME = T.SEASON AND F15_SUB.YEARID = T.YEARID

UNION ALL

SELECT 
 W15_SUB.*,
 COALESCE(T.TERMKEY,-1) 
FROM(
	SELECT DISTINCT --DUPLICATE ENTRIES IN THIS TABLE
		STUDENTID,
		MEASUREMENTSCALE,
		'Winter' AS TERMNAME,
		25 AS YEARID,--LEFT(TERMNAME,CHARINDEX(' ',TERMNAME,0)) TERMNAME,
		CONVERT(DATE,TESTSTARTDATE) TESTDATE,
		[WINTERtoWINTERConditionalGrowthIndex] ANNUAL_CGI,
		[WINTERtoWINTERConditionalGrowthPercentile] ANNUAL_GP,
		[FALLToWinterConditionalGrowthIndex] WINDOW_CGI,
		[FALLToWinterConditionalGrowthPercentile] WINDOW_GP,
		SC.SCHOOL_NUMBER
		FROM [test_nweamap].[Test_NWEAMAP_MAPRawData_v3] W15
		JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SC ON SC.NAME = W15.SCHOOLNAME 
		WHERE STUDENTID != 'StudentID'
		and MEASUREMENTSCALE != 'Mathematics'
	) W15_SUB
LEFT JOIN CUSTOM.CUSTOM_EARLY_WARNING_TERMS T ON T.SCHOOLID = W15_SUB.SCHOOL_NUMBER AND W15_SUB.TERMNAME = T.SEASON AND W15_SUB.YEARID = T.YEARID
;

DROP TABLE CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_READING;

CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_READING (
STUDENT_NUMBER INT,
TESTSUBJECT VARCHAR(20),
TESTPERIOD VARCHAR(10),
YEARID INT,
TESTDATE DATE,
ANNUAL_CGI FLOAT(5),
ANNUAL_GP INT,
WINDOW_CGI FLOAT(5),
WINDOW_GP INT,
SCHOOL_NUMBER INT,
TERMKEY INT)

CREATE INDEX EW_ASSESSMENT_GROWTH_READING ON CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_READING (STUDENT_NUMBER,TERMKEY);

INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_GROWTH_READING
SELECT 
 F15_SUB.*,
 COALESCE(T.TERMKEY,-1)
FROM (
	SELECT 
		STUDENTID,
		MEASUREMENTSCALE,
		'Fall' AS TERMNAME,
		25 AS YEARID,
		CONVERT(DATE,TESTSTARTDATE) TESTDATE,
		[FallToFallConditionalGrowthIndex] ANNUAL_CGI,
		[FallToFallConditionalGrowthPercentile] ANNUAL_GP,
		NULL WINDOW_CGI,
		NULL WINDOW_GP,
		SC.SCHOOL_NUMBER
		FROM [test_nweamap].[Test_NWEAMAP_MAPRawData_v2] F15
		JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SC ON SC.NAME = F15.SCHOOLNAME 
		WHERE STUDENTID != 'StudentID'
		AND MEASUREMENTSCALE = 'Reading'
	) F15_SUB
LEFT JOIN CUSTOM.CUSTOM_EARLY_WARNING_TERMS T ON T.SCHOOLID = F15_SUB.SCHOOL_NUMBER AND F15_SUB.TERMNAME = T.SEASON AND F15_SUB.YEARID = T.YEARID

UNION ALL

SELECT 
 W15_SUB.*
, COALESCE(T.TERMKEY,-1)
FROM(
	SELECT DISTINCT --DUPLICATE ENTRIES IN THIS TABLE
		STUDENTID,
		MEASUREMENTSCALE,
		'Winter' AS TERMNAME,
		25 AS YEARID,--LEFT(TERMNAME,CHARINDEX(' ',TERMNAME,0)) TERMNAME,
		CONVERT(DATE,TESTSTARTDATE) TESTDATE,
		[WINTERtoWINTERConditionalGrowthIndex] ANNUAL_CGI,
		[WINTERtoWINTERConditionalGrowthPercentile] ANNUAL_GP,
		[FALLToWinterConditionalGrowthIndex] WINDOW_CGI,
		[FALLToWinterConditionalGrowthPercentile] WINDOW_GP,
		SC.SCHOOL_NUMBER
		FROM [test_nweamap].[Test_NWEAMAP_MAPRawData_v3] W15
		JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SC ON SC.NAME = W15.SCHOOLNAME 
		WHERE STUDENTID != 'StudentID'
		and MEASUREMENTSCALE != 'Reading'
	) W15_SUB
LEFT JOIN CUSTOM.CUSTOM_EARLY_WARNING_TERMS T ON T.SCHOOLID = W15_SUB.SCHOOL_NUMBER AND W15_SUB.TERMNAME = T.SEASON AND W15_SUB.YEARID = T.YEARID;
*/
