/****** SCRIPT FOR SELECTTOPNROWS COMMAND FROM SSMS  ******/
--DROP TABLE CUSTOM.CUSTOM_EARLY_WARNING_RIT_TO_READING;

CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_RIT_TO_READING(
TERMNAME VARCHAR(25),
TERMKEY INT,
SEASON VARCHAR(25),
YEARID INT,
STUDENT_NUMBER INT,
STUDENTID INT,
STUDENTKEY INT,
TESTSTARTDATE DATE,
SCHOOLNAME VARCHAR(50),
SCHOOL_NUMBER INT,
RITTOREADINGSCORE INT,
RITTOREADINGMIN INT,
RITTOREADINGMAX INT)

CREATE INDEX EW_RITTOREADING ON CUSTOM.CUSTOM_EARLY_WARNING_RIT_TO_READING (STUDENTKEY,TERMKEY);

INSERT INTO
SELECT 
 R.TERMNAME
,EWS_T.TERMKEY
,LEFT(R.TERMNAME,CHARINDEX(' ',R.TERMNAME)) AS SEASON
,PS_T.YEARID
,STUDENTID AS STUDENT_NUMBER
,S.ID AS STUDENTID
,DS.STUDENTKEY
,TESTSTARTDATE
,SCHOOLNAME
,SCHOOL_NUMBER
,CASE 
	WHEN [RITTOREADINGSCORE] = 'BR' THEN -1
	WHEN [RITTOREADINGSCORE] IS NULL THEN NULL
	ELSE CAST([RITTOREADINGSCORE] AS INT)
 END AS RITTORREADINGSCORE
,CASE 
	WHEN [RITTOREADINGMIN] = 'BR' THEN -1
	WHEN [RITTOREADINGMIN] IS NULL THEN NULL
	ELSE CAST([RITTOREADINGMIN] AS INT)
 END AS RITTORREADINGMIN	
,CASE 
	WHEN [RITTOREADINGMAX] = 'BR' THEN -1
	WHEN [RITTOREADINGMAX] IS NULL THEN NULL
	ELSE CAST([RITTOREADINGMAX] AS INT)
 END AS RITTORREADINGMAX	 
FROM [CUST1220].[CUSTOM].[CUSTOM_MAP_RITTOREADING] R
JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SC ON SC.NAME = R.SCHOOLNAME 
JOIN [POWERSCHOOL].[POWERSCHOOL_TERMS] PS_T ON R.TESTSTARTDATE BETWEEN PS_T.FIRSTDAY AND PS_T.LASTDAY AND SC.SCHOOL_NUMBER = PS_T.SCHOOLID AND PS_T.ID LIKE '%00'
JOIN [CUSTOM].[CUSTOM_EARLY_WARNING_TERMS] EWS_T ON LEFT(R.TERMNAME,CHARINDEX(' ',R.TERMNAME)) = EWS_T.SEASON AND PS_T.YEARID = EWS_T.YEARID AND SC.SCHOOL_NUMBER = EWS_T.SCHOOLID
JOIN [custom].[custom_StudentBridge] SB ON SB.STUDENT_NUMBER = R.STUDENTID
JOIN DW.DW_DIMSTUDENT DS ON DS.SYSTEMSTUDENTID = SB.SYSTEMSTUDENTID
JOIN POWERSCHOOL.POWERSCHOOL_STUDENTS S ON S.STUDENT_NUMBER = R.STUDENTID;
