IF OBJECT_ID('CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_MATH','U') IS NOT NULL
	DELETE FROM CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_MATH

ELSE
	CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_MATH(
	STUDENT_NUMBER INT,
	STUDENTID INT,
	SYSTEMSTUDENTID VARCHAR(25),
	STUDENTKEY INT,
	SCALESCORE INT,
	PERCENTILESCORE INT,
	TESTPERIOD VARCHAR(10),
	TESTDATE DATE,
	TESTSUBJECT VARCHAR(20),
	TERMKEY INT,
	LASTUPDATED DATETIME);

IF (SELECT OBJECT_ID
	FROM sys.indexes 
	WHERE name='EW_ASSESSMENT_SCORES_MATH' AND object_id = OBJECT_ID('CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_MATH')) IS NULL
	CREATE INDEX EW_ASSESSMENT_SCORES_MATH ON CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_MATH (STUDENT_NUMBER,TERMKEY);

INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_MATH --APPARENTLY DON'T NEED TO THE DEFINE THE FIELDS AT BEGINNING OF INSERT STATEMENT
SELECT --MATHEMATICS SCORES
PS.STUDENT_NUMBER,
PS.ID AS STUDENTID,
S.SYSTEMSTUDENTID,
S.STUDENTKEY,
SCALESCORE,
PERCENTILESCORE,
TESTPERIOD,	
TESTDATE,
TESTSUBJECT,
COALESCE(TERMS.TERMKEY,-1) AS "TERMKEY",--IF TERM KEY IS NULL THEN MAKE IT -1
GETDATE()
FROM [dw].[DW_factTestScores] F
JOIN [dw].[DW_dimTest] T ON T.TESTKEY = F.TESTKEY
JOIN [dw].[DW_dimStudent] S on S.STUDENTKEY = F.STUDENTKEY
JOIN [custom].[custom_StudentBridge] SB ON SB.SYSTEMSTUDENTID = S.SYSTEMSTUDENTID
JOIN [powerschool].[powerschool_Students] PS ON PS.STUDENT_NUMBER = SB.SYSTEMSTUDENTID
JOIN [dw].[DW_dimSchool] SC ON SC.SCHOOLKEY = F.SCHOOLKEY
JOIN [dw].[DW_dimSchoolCalendar] C ON C.SCHOOLCALENDARKEY = F.SCHOOLCALENDARKEY
LEFT JOIN [custom].CUSTOM_EARLY_WARNING_TERMS TERMS ON RIGHT(C.SCHOOLYEAR4DIGIT,2)+9 = TERMS.YEARID AND TERMS.SEASON = TESTPERIOD AND CAST(SC.SYSTEMSCHOOLID AS INT) = TERMS.SCHOOLID 
WHERE TESTTYPE = 'NWEA MAP'
AND TESTSUBJECT = 'Mathematics'
AND TESTSCORETYPE = 'Test'
AND SC.SYSTEMSCHOOLID!='-----'
AND TESTDATE>='08-01-2010' --Don't include tests before 10-11 school year
;


IF OBJECT_ID('CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_READING','U') IS NOT NULL
	DELETE FROM CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_READING

ELSE
	CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_READING(
	STUDENT_NUMBER INT,
	STUDENTID INT,
	SYSTEMSTUDENTID VARCHAR(25),
	STUDENTKEY INT,
	SCALESCORE INT,
	PERCENTILESCORE INT,
	TESTPERIOD VARCHAR(10),
	TESTDATE DATE,
	TESTSUBJECT VARCHAR(20),
	TERMKEY INT,
	LASTUPDATED DATETIME);
	
IF (SELECT OBJECT_ID
	FROM sys.indexes 
	WHERE name='EW_ASSESSMENT_SCORES_READING' AND object_id = OBJECT_ID('CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_READING')) IS NULL
	CREATE INDEX EW_ASSESSMENT_SCORES_READING ON CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_READING (STUDENT_NUMBER,TERMKEY);


INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_ASSESSMENT_SCORES_READING --APPARENTLY DON'T NEED TO THE DEFINE THE FIELDS AT BEGINNING OF INSERT STATEMENT
SELECT --READING SCORES
PS.STUDENT_NUMBER,
PS.ID AS STUDENTID,
S.SYSTEMSTUDENTID,
S.STUDENTKEY,
SCALESCORE,
PERCENTILESCORE,
TESTPERIOD,
TESTDATE,
TESTSUBJECT,
COALESCE(TERMS.TERMKEY,-1) AS TERMKEY,--IF TERM KEY IS NULL THEN MAKE IT -1
GETDATE()
FROM [dw].[DW_factTestScores] F
JOIN [dw].[DW_dimTest] T ON T.TESTKEY = F.TESTKEY
JOIN [dw].[DW_dimStudent] S on S.STUDENTKEY = F.STUDENTKEY
JOIN [custom].[custom_StudentBridge] SB ON SB.SYSTEMSTUDENTID = S.SYSTEMSTUDENTID
JOIN [powerschool].[powerschool_Students] PS ON PS.STUDENT_NUMBER = SB.SYSTEMSTUDENTID
JOIN [dw].[DW_dimSchool] SC ON SC.SCHOOLKEY = F.SCHOOLKEY
JOIN [dw].[DW_dimSchoolCalendar] C ON C.SCHOOLCALENDARKEY = F.SCHOOLCALENDARKEY
LEFT JOIN [custom].CUSTOM_EARLY_WARNING_TERMS TERMS ON RIGHT(C.SCHOOLYEAR4DIGIT,2)+9 = TERMS.YEARID AND TERMS.SEASON = TESTPERIOD AND CAST(SC.SYSTEMSCHOOLID AS INT) = TERMS.SCHOOLID 
WHERE TESTTYPE = 'NWEA MAP'
AND TESTSUBJECT = 'Reading'
AND TESTSCORETYPE = 'Test'
AND SC.SYSTEMSCHOOLID!='-----'
AND TESTDATE>='08-01-2010' --Don't include tests before 10-11 school year
