IF OBJECT_ID('CUSTOM.CUSTOM_EARLY_WARNING_STEP','U') IS NOT NULL
	DELETE FROM CUSTOM.CUSTOM_EARLY_WARNING_STEP
ELSE
	CREATE TABLE CUSTOM.CUSTOM_EARLY_WARNING_STEP (
	STUDENT_NUMBER INT,
	STUDENTID INT,
	STUDENTKEY INT,
	SYSTEMSTUDENTID VARCHAR(25),
	TERMKEY INT,
	TESTSCORE INT,
	PROFICIENCYLEVEL VARCHAR(20),
	LASTUPDATED DATETIME);

IF (SELECT OBJECT_ID
	FROM sys.indexes 
	WHERE name='EW_STEP' AND object_id = OBJECT_ID('CUSTOM.CUSTOM_EARLY_WARNING_STEP')) IS NULL
	CREATE INDEX EW_STEP ON CUSTOM.CUSTOM_EARLY_WARNING_STEP (STUDENT_NUMBER,TERMKEY);


INSERT INTO CUSTOM.CUSTOM_EARLY_WARNING_STEP
SELECT
[POWERSCHOOL_STUDENTS].STUDENT_NUMBER,
[POWERSCHOOL_STUDENTS].ID,
[TEST SCORES].STUDENTKEY,
[STUDENT].SYSTEMSTUDENTID,
TERMKEY,
TESTSCORE,
PROFICIENCYLEVEL,
GETDATE()
FROM [dw].[DW_factTestScores] [TEST SCORES]
INNER JOIN [dw].[DW_dimTest] [TEST] ON [TEST].TESTKEY = [TEST SCORES].TESTKEY
INNER JOIN [dw].[DW_dimTestProficiencyLevel] [PROFICIENCY] ON [PROFICIENCY].TESTPROFICIENCYLEVELKEY = [TEST SCORES].TESTPROFICIENCYLEVELKEY
INNER JOIN [dw].[DW_dimSchoolCalendar] [CALENDAR] ON [CALENDAR].SCHOOLCALENDARKEY = [TEST SCORES].SCHOOLCALENDARKEY
INNER JOIN [dw].[DW_dimSchool] [SCHOOL] ON [SCHOOL].SCHOOLKEY = [TEST SCORES].SCHOOLKEY
INNER JOIN [dw].[DW_dimStudent] [STUDENT] ON [STUDENT].STUDENTKEY = [TEST SCORES].STUDENTKEY
INNER JOIN [CUSTOM].[CUSTOM_STUDENTBRIDGE] [CUSTOM_STUDENTBRIDGE] ON ([STUDENT].[SYSTEMSTUDENTID] = [CUSTOM_STUDENTBRIDGE].[SYSTEMSTUDENTID])
INNER JOIN [POWERSCHOOL].[POWERSCHOOL_STUDENTS] [POWERSCHOOL_STUDENTS] ON ([CUSTOM_STUDENTBRIDGE].[STUDENT_NUMBER] = [POWERSCHOOL_STUDENTS].[STUDENT_NUMBER])
INNER JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SCH ON SCH.ABBREVIATION = SCHOOL.SCHOOLNAME_ABBREVIATION
LEFT JOIN CUSTOM.CUSTOM_EARLY_WARNING_STEP_TERM_CONVERSION [STEP TERMS] ON [STEP TERMS].SCHOOLYEAR4DIGIT = [CALENDAR].SCHOOLYEAR4DIGIT AND [STEP TERMS].TESTPERIOD = [TEST].TESTPERIOD AND [STEP TERMS].SCHOOLID = SCH.SCHOOL_NUMBER --possibly combine this into the custom_term_conversion view
INNER JOIN CUSTOM.CUSTOM_EARLY_WARNING_TERMS [TERMS] ON [TERMS].SCHOOLYEAR4DIGIT = [CALENDAR].SCHOOLYEAR4DIGIT AND [TERMS].SCHOOLID = SCH.SCHOOL_NUMBER AND [STEP TERMS].COMMONTERM = [TERMS].COMMONTERM
WHERE [TEST].[TESTTYPE] = 'STEP'
AND [TEST].TESTSCORETYPE = 'Cycle'
